catering:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRP9Jg4cpBAs2NWABKi
    access-key-secret: mkzy04Xok3XTZRyfykfteGRxn3pvW8
    bucket-name: sky-bruce-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxf099694100270d19
    secret: dbdfb7ab0341d7e4ca54ed995ccbef5e